# -*- coding: utf-8 -*-
"""ObjectDetection lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGinQsFhPz686yVQNREd7xKaisHJHHIk
"""

from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()
detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath(os.path.join(execution_path,"resnet50_coco_best_v2.1.0.h5"))
detector.loadModel()
detection_list = detector.detectObjectsFromImage(execution_path,"image.jpg"),output_image_path=os.path.join(execution_path , "imagenew.jpg"))
for everyObject in detections:
  print(everyObject["name"])

"""//pip install tensorflow==2.4.0
//pip install keras==2.4.3  numpy==1.19.3 pillow==7.0.0 scipy==1.4.1 h5py==2.10.0 matplotlib==3.3.2 opencv-python keras-resnet==0.2.0
//pip install imageai --upgrade

"""